apiVersion: apps/v1
kind: Deployment
metadata:
  name: classroom-spring-demo
  labels:
    tier: backend
    app: classroom-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      app: classroom-demo
  template:
    metadata:
      labels:
        tier: backend
        app: classroom-demo
    spec:
      containers:
        - name: classroom-spring-demo
          image: alexc/classroomdemo:latest # alexc/classroomdemo:latest
          imagePullPolicy: Never
          env:
            - name: MYSQL_URL
              value: mysql
          ports:
            - containerPort: 8080