kind: Service
apiVersion: v1
metadata:
  name: service-classroom-spring-demo
spec:
  selector:
    app: classroom-demo
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort