apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service-classroom-spring-demo
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: classroom-demo
    tier: backend